networks:
  quakening:
services:
  quake: 
    restart: unless-stopped
    build:
      dockerfile: ./dev/Dockerfile.quake
      target: hfq-quake-server
    image: hf-quake
    container_name: quake
    networks: [ quakening ]
    ports: [ "27960:27960" ]
    working_dir: /opt/ioq3
    environment:
      - QUAKE_GAME=${QUAKE_GAME:-hf}
    command: sh bin/quake.sh
  web:
    # TODO(sissel): Add ioquake3.js from quakebuild
    image: hf-web
    container_name: web
    build:
      dockerfile: ./dev/Dockerfile.quake
      target: hfq-web
    ports:
      - 8080:80
    networks: [ quakening ]
