networks:
  quakening:
services:
  quake: 
    restart: unless-stopped
    container_name: quake
    build:
      context: ./dev
      dockerfile: ./Dockerfile.quake
    image: quakebuild:latest
    networks: [ quakening ]
    ports: [ "27960:27960" ]
    volumes: 
      - ./assets:/opt/ioq3/assets
      - ./base:/opt/ioq3/base
      - ./bin:/opt/ioq3/bin
    working_dir: /opt/ioq3
    environment:
      - QUAKE_GAME=${QUAKE_GAME:-hf}
    command: sh bin/quake.sh
  web:
    # TODO(sissel): Add ioquake3.js from quakebuild
    image: quakebuild
    container_name: quake-web
    working_dir: /srv/quakejs
    ports:
      - 8080:8080
    networks: [ quakening ]
    # TODO(sissel): Copy this into the image instead of using volumes
    volumes:
      - ./html:/srv/quakejs/html
    command: sh -c 'cp /opt/ioq3/build/release-js-js/ioquake3.js; cd html; python3 -mhttp.server 8080'
  assets: 
    container_name: quake-assets
    image: quake-assets
    build:
      context: ./dev
      dockerfile: ./Dockerfile.assets
    volumes:
      - ./base/hf:/srv/quake-assets/assets/hf
    ports: [ "9000:9000" ]
    networks: [ quakening ]
    command: /bin/sh -c 'node bin/content.js' -


