networks:
  quakening:
services:
  quake: 
    restart: unless-stopped
    container_name: quake
    build:
      context: ./dev
    image: quakebuild:latest
    networks: [ quakening ]
    ports: [ "27960:27960" ]
    volumes: 
      - ./assets:/tmp/ioq3/assets
      - ./base:/tmp/ioq3/base
      - ./bin:/tmp/ioq3/bin
    working_dir: /tmp/ioq3
    environment:
      - QUAKE_GAME=${QUAKE_GAME:-hf}
    command: sh bin/quake.sh
  web:
    image: python:3.12-bookworm
    container_name: quake-web
    working_dir: /srv/quakejs
    ports:
      - 8080:8080
    networks: [ quakening ]
    volumes:
      - ./html:/srv/quakejs/html
    command: sh -c 'cd html; python3 -mhttp.server 8080'
  assets: 
    container_name: quake-assets
    image: quakebuild:latest # contains nodejs
    ports: [ "9000:9000" ]
    networks: [ quakening ]
    working_dir: /srv/quakejs
    volumes:
      - ./bin:/srv/quakejs/bin
      - ./package.json:/srv/quakejs/package.json
      - ./node_modules:/srv/quakejs/node_modules
      - ./assets:/srv/quakejs/assets
    command: /bin/sh -c 'npm i && node bin/content.js' -


