
# We need an OS base that still ships python2
# Debian 12 ("bookworm") doesn't ship python2 anymore.
# Note: Debian 11 goes EOL in 2026.
# Might be worth archiving the docker image this creates somewhere before then.
FROM debian:11

RUN apt-get update
RUN apt-get install -y python2 clang make
RUN apt-get remove -y gcc g++
RUN apt-get install -y wget curl
RUN apt-get install -y cmake

RUN mkdir -p /tmp/build/emscripten-fastcomp

ENV EMSCRIPTEN_VERSION=1.38.22

# Build emscripten-fastcomp. 
# This is a fork of llvm from early in Emscripten's life. It's no longer needed
# on recent releases because Emscripten upstreamed changes into LLVM. However,
# for older versions like we are using, the old llvm fork "emscripten-fastcomp"
# is required.
RUN wget -O- https://github.com/Forklifts-For-Great-Justice/emscripten-fastcomp/archive/refs/tags/${EMSCRIPTEN_VERSION}.tar.gz | tar -zx -C /tmp

#RUN wget https://releases.llvm.org/6.0.1/cfe-6.0.1.src.tar.xz
#RUN mkdir -p /tmp/clang
#RUN tar -xf cfe-6.0.1.src.tar.xz --strip 1 -C /tmp/clang 
#RUN rm cfe-6.0.1.src.tar.xz

# Get emscripten clang fastcomp fork at the same version
RUN mkdir /tmp/clang
RUN wget -O- https://github.com/Forklifts-For-Great-Justice/emscripten-fastcomp-clang/archive/refs/tags/${EMSCRIPTEN_VERSION}.tar.gz | tar -zx --strip-components 1 -C /tmp/clang

# Version 1.38.22 seems to need clang put into the parent dir: emscripten-fastcomp/../clang
# Version 1.29.12 seems to need clang put into the source dir: emscripten-fastcomp/tools/clang

RUN apt-get install -y python2 git
RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 0

WORKDIR /tmp/build/emscripten-fastcomp
RUN ls /tmp ; sleep 3
RUN cmake /tmp/emscripten-fastcomp-${EMSCRIPTEN_VERSION} -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD='JSBackend;X86'

RUN echo "\"${EMSCRIPTEN_VERSION}\"" >> emscripten-version.txt
#RUN echo "\"${EMSCRIPTEN_VERSION}\"" >> /tmp/clang/emscripten-version.txt

RUN cmake --build . --parallel 4
RUN make install DESTDIR=/tmp/llvm

RUN wget -O- https://github.com/emscripten-core/emscripten/archive/refs/tags/${EMSCRIPTEN_VERSION}.tar.gz | tar -zx -C /tmp

RUN apt-get install -y nodejs

RUN git clone https://github.com/begleysm/ioq3 /tmp/ioq3
#RUN git clone https://github.com/Forklifts-For-Great-Justice/quakejs /tmp/quakejs
#WORKDIR /tmp/quakejs
#RUN git submodule update --init

WORKDIR /tmp/ioq3
RUN echo "PATH=/tmp/llvm/usr/local/bin:$PATH LLVM=/tmp/llvm/usr/local/bin make PLATFORM=js EMSCRIPTEN=/tmp/emscripten-${EMSCRIPTEN_VERSION}/" > /build.sh
