FROM quakebuild:latest

ENV EMSCRIPTEN_VERSION=1.38.22

WORKDIR /tmp
RUN wget -O emscripten.tar.gz https://github.com/emscripten-core/emscripten/archive/refs/tags/${EMSCRIPTEN_VERSION}.tar.gz
RUN tar -zxf emscripten.tar.gz
RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 0
WORKDIR /tmp/emscripten-${EMSCRIPTEN_VERSION}

ENV LLVM_ROOT=/tmp/build/emscripten-fastcomp/
