ARG GAME_ASSETS_IMAGE=ghcr.io/forklifts-for-great-justice/quakejs/assets@sha256:ebeb40dc50e4ced3bead39d00fa0a898fb89dc457b44dde459ec11185e4ce9eb

FROM debian:11 AS base_os
RUN apt-get update

# Prepare packages for installation, but don't install until later
# This hopefully makes image building more reliable and faster by skipping
# duplicate downloads and only installing packages needed on each image,
# as needed.
RUN apt-get install -y --download-only --no-install-recommends bison clang cmake curl git groff make nodejs npm python2 unzip wget zip

# Stop docker from purging the apt download cache after it runs so future images can use this cache.
RUN rm /etc/apt/apt.conf.d/docker-clean

# Most things will need ca-certificates, so do it now.
RUN apt-get install -y --no-install-recommends ca-certificates

# We need an OS base that still ships python2
# Debian 12 ("bookworm") doesn't ship python2 anymore.
# Note: Debian 11 goes EOL in 2026.
# Might be worth archiving the docker image this creates somewhere before then.
FROM base_os AS ioq3-toolchain

RUN apt-get install -y --no-install-recommends wget curl cmake python2 git clang make bison

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 0

# Our fork of ioq3 requires a very old version of emscripten.
ENV EMSCRIPTEN_VERSION=1.13.2

WORKDIR /tmp

# Build emscripten-fastcomp. 
# This is a fork of llvm from early in Emscripten's life. It's no longer needed
# on recent releases because Emscripten upstreamed changes into LLVM. However,
# for older versions like we are using, the old llvm fork "emscripten-fastcomp"
# is required.
RUN git clone --branch "${EMSCRIPTEN_VERSION}" --single-branch https://github.com/Forklifts-For-Great-Justice/emscripten-fastcomp

# FYI:
# Version 1.38.22 seems to need clang put into the parent dir: emscripten-fastcomp/../clang
# Version 1.29.12 seems to need clang put into the source dir: emscripten-fastcomp/tools/clang

# emscripten-fastcomp 1.13.x(?) has a typo in a CMakeList dependency entry
RUN sed -ie 's/intinsics/intrinsics/' /tmp/emscripten-fastcomp/lib/Bitcode/NaCl/Writer/CMakeLists.txt

# 1.13.x: clang must be in srcdir/tools/clang, otherwise it will fail to build
#   clang with an error about not finding "../../Makefile"
WORKDIR /tmp/emscripten-fastcomp
RUN [ -d ./tools ] || mkdir ./tools
# Get emscripten clang fastcomp fork at the same version
RUN git clone --branch "${EMSCRIPTEN_VERSION}" --single-branch https://github.com/Forklifts-For-Great-Justice/emscripten-fastcomp-clang ./tools/clang

# For 1.19.x and older? LLVM/emscripten-fastcomp uses ./configure, not cmake?
RUN ./configure --with-clang-srcdir=./tools/clang --enable-cxx11 --enable-targets=js,x86_64 CFLAGS=-Wno-everything CXXFLAGS=-Wno-everything

# Build it. -j12 seems to work OK with 1.13.2
RUN make -j12 #VERBOSE=1

# 1.13.2 requires groff
RUN apt-get install -y --no-install-recommends groff
RUN make install DESTDIR=/opt/llvm
RUN mkdir /opt/emscripten
RUN git clone --branch "${EMSCRIPTEN_VERSION}" --single-branch https://github.com/emscripten-core/emscripten /opt/emscripten

#### Compile ioq3 from source
FROM base_os AS hfq-ioq3-build-warmup
COPY --from=ioq3-toolchain /opt/llvm /opt/llvm
COPY --from=ioq3-toolchain /opt/emscripten /opt/emscripten

RUN apt-get install -y --no-install-recommends clang nodejs npm git python2 make bison curl

# quake qvm compilation seems to invoke 'gcc' directly. 
# Possible we can remove this in the future if that is fixed.
RUN apt-get install -y --no-install-recommends gcc

# Make emscripten's first-run config setup happen.
# There may be a better way to bypass this other than running the emmake tool twice
ENV LLVM=/opt/llvm/usr/local/bin 
ENV EMSCRIPTEN=/opt/emscripten

# Let emscripten do a first-run startup
RUN PATH=${LLVM}:$PATH ${EMSCRIPTEN}/emmake --generate-config

RUN mkdir -p /opt/ioq3
WORKDIR /opt/ioq3

# The debian node-ws package is far too new and is incompatible with this
# version of emscripten
RUN mkdir node_modules && npm i ws@0.4.29

ADD ./ioq3 /opt/ioq3

ADD dev/patch-quake.sh /tmp
RUN sh /tmp/patch-quake.sh

ADD dev/build-quake.sh /tmp
RUN sh /tmp/build-quake.sh

FROM hfq-ioq3-build-warmup AS hfq-ioq3-build

# Use the local ioq3 files to build any new changes
# This reuses the build from the -warmup stage since we're not likely changing all that many files in quake.
# Hopefully this speeds up by effectively doing incremental builds.

ADD ./ioq3/code /opt/ioq3/code
ADD ./ioq3/Makefile /opt/ioq3/Makefile

ADD dev/patch-quake.sh /tmp
RUN sh /tmp/patch-quake.sh

ADD dev/build-quake.sh /tmp
RUN sh /tmp/build-quake.sh

#### Gather original quake asset files
# These files were previously available on content.quakejs.com, but
# that has since been taken offline as the original author has begun a
# new quake project... So, we'll pull the quake installer assets from
# a previous docker image we built.
FROM $GAME_ASSETS_IMAGE AS hfq-quake-assets-installer

#### Collect the base game assets
FROM base_os AS hfq-quake-assets

RUN mkdir -p /opt/ioq3
WORKDIR /opt/ioq3
RUN mkdir assets

# ioq3 bootstraps itself by fetching the shareware(?) linux quake3 installer scripts and unpacking the tarball at runtime.
# It's weird, I know...
COPY --from=hfq-quake-assets-installer /srv/quake-assets/assets/296843703-linuxq3apoint-1.32b-3.x86.run /opt/ioq3/assets
COPY --from=hfq-quake-assets-installer /srv/quake-assets/assets/857908472-linuxq3ademo-1.11-6.x86.gz.sh /opt/ioq3/assets

# Add hardlinks for the quake server which looks for these files without the crc file prefix
RUN cd assets; ln 857908472-linuxq3ademo-1.11-6.x86.gz.sh linuxq3ademo-1.11-6.x86.gz.sh 
RUN cd assets; ln 296843703-linuxq3apoint-1.32b-3.x86.run linuxq3apoint-1.32b-3.x86.run

FROM base_os AS hfq-quake-external-assets
RUN apt-get install -y --no-install-recommends curl unzip zip libarchive-zip-perl

RUN mkdir -p /opt/ioq3
WORKDIR /opt/ioq3
RUN mkdir assets

ADD dev/get_assets.sh /tmp
RUN sh /tmp/get_assets.sh

COPY dev/pk3prep.sh /tmp
RUN bash /tmp/pk3prep.sh /opt/ioq3/

FROM base_os AS hfq-quake-internal-assets
RUN apt-get install -y --no-install-recommends curl unzip zip libarchive-zip-perl
# libarchive-zip-perl provides a crc32 program we need :)

# Fetch our q3 mod code into a pakfile (and ship it as pak100.pk3)
# Maybe move this into the quake build script...
COPY --from=hfq-ioq3-build /opt/ioq3/build/release-js-js/baseq3/vm /tmp/vm
RUN mkdir -p /opt/ioq3/assets/hf
RUN cd /tmp/; zip -r /opt/ioq3/assets/hf/pak100.pk3 ./vm

# Fetch our modified in-game assets (and ship it as pak101.pk3)
COPY hf/buildpak3.sh /opt/quakejs/hf/
COPY hf/sounds /opt/quakejs/hf/sounds/
RUN cd /opt/quakejs && sh hf/buildpak3.sh && mv hf/build/pak101.pk3 /opt/ioq3/assets/hf/

COPY dev/pk3prep.sh /tmp
RUN bash /tmp/pk3prep.sh /opt/ioq3/

#### Generate the ioq3 manifest file
FROM node:26 AS hfq-node

COPY package.json /opt/ioq3/
COPY package-lock.json /opt/ioq3/
WORKDIR /opt/ioq3

RUN npm i

#### Generate the asset manifest that ioq3 uses to fetch pak files
FROM hfq-node AS hfq-quake-manifest

COPY bin/manifest.cjs /opt/ioq3/
COPY --from=hfq-quake-external-assets /opt/ioq3/assets /opt/ioq3/assets
COPY --from=hfq-quake-assets /opt/ioq3/assets /opt/ioq3/assets
COPY --from=hfq-quake-internal-assets /opt/ioq3/assets /opt/ioq3/assets

# This is expected to write to /opt/ioq3/assets/manifest.json
RUN node manifest.cjs

FROM hfq-node AS hfq-shenanigans

COPY hf/shenanigans /opt/ioq3/hf/shenanigans
COPY tsconfig.json /opt/ioq3/

RUN npm exec tsc
COPY hf/shenanigans /opt/ioq3/html/hf/shenanigans

#### Content to be served to clients over the web (assets, quake client, javascript shenanigans, etc)
FROM nginx:1.31.3 AS hfq-web

# index.html and friends.
COPY html/index.html /usr/share/nginx/html/
COPY html/game.css /usr/share/nginx/html/

# Quake client code from ioq3 build
COPY --from=hfq-ioq3-build /opt/ioq3/build/release-js-js/ioquake3.js /usr/share/nginx/html/ioquake3.js
COPY --from=hfq-ioq3-build /opt/ioq3/build/release-js-js/ioquake3.js.map /usr/share/nginx/html/ioquake3.js.map

# Base quake3 assets
COPY --from=hfq-quake-assets /opt/ioq3/assets /usr/share/nginx/html/assets

# Bring in external assets
COPY --from=hfq-quake-external-assets /opt/ioq3/assets /usr/share/nginx/html/assets

# Internal assets like code and asset modifications
COPY --from=hfq-quake-internal-assets /opt/ioq3/assets /usr/share/nginx/html/assets

# And the manifest file
COPY --from=hfq-quake-manifest /opt/ioq3/assets/manifest.json /usr/share/nginx/html/assets/manifest.json

# Shenanigans!
COPY --from=hfq-shenanigans /opt/ioq3/html/ /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html

#### This target contains a usable quake server.
FROM base_os AS hfq-quake-server

RUN apt-get install -y --no-install-recommends nodejs

RUN mkdir -p /opt/ioq3/bin/

ADD dev/quake.sh /opt/ioq3/bin/quake.sh
COPY --from=hfq-ioq3-build /opt/ioq3/build/release-js-js/ioq3ded.js /opt/ioq3/build/release-js-js/ioq3ded.js 
COPY --from=hfq-ioq3-build /opt/ioq3/node_modules /opt/ioq3/node_modules

COPY ./server.cfg /opt/ioq3/base/hf/

# Base quake3 assets
COPY --from=hfq-quake-assets /opt/ioq3/assets /opt/ioq3/assets

# Bring in external assets
COPY --from=hfq-quake-external-assets /opt/ioq3/assets /opt/ioq3/assets

# Internal assets like code and asset modifications
COPY --from=hfq-quake-internal-assets /opt/ioq3/assets /opt/ioq3/assets

WORKDIR /opt/ioq3

RUN find /var/cache/apt -name '*.deb' -delete

