FROM debian:11 AS base_assets

RUN apt-get update
RUN apt-get install -y jq wget

RUN mkdir /srv/quake-assets
WORKDIR /srv/quake-assets
ADD get_assets.sh .
RUN bash get_assets.sh

FROM base_assets

RUN apt-get install -y git nodejs npm
RUN git clone --depth 1 https://github.com/Forklifts-For-Great-Justice/quakejs.git 

RUN cp quakejs/dev/assets-package.json ./package.json
RUN npm i

RUN mkdir bin; cp quakejs/bin/content.js bin
