---
name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        context: [ dev ]
        include:
        - dockerfile: "dev/Dockerfile.quake"
          name: quake
        - dockerfile: "dev/Dockerfile.assets"
          name: assets

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.registry }}/${{ github.repository }}/${{ matrix.name }}

      - name: Log in to the Container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ format('{0} - Build{1}Docker image', matrix.name, (github.event_name == 'push' && '+Push ' || ' ')) }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64"
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max