---
name: Docker Image CI

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta_quake
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.registry }}/${{ github.repository }}/hfq-quake

      - name: ${{ format('Build{0}Quake Server', (github.event_name == 'push' && '+Push ' || ' ')) }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_quake.outputs.tags }}
          labels: ${{ steps.meta_quake.outputs.labels }}
          platforms: "linux/amd64"
          context: .
          target: hfq-quake-server
          file: dev/Dockerfile.quake
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels)
        id: meta_web
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.registry }}/${{ github.repository }}/hfq-web

      - name: ${{ format('Build{0}Web and Assets', (github.event_name == 'push' && '+Push ' || ' ')) }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
          platforms: "linux/amd64"
          context: .
          target: hfq-web
          file: dev/Dockerfile.quake
          cache-from: type=gha
          cache-to: type=gha,mode=max
