---
name: pak100 - Quake Code Modifications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  registry: ghcr.io

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # XXX: dev.sh can do this, but not in the context of Github Actions
      # XXX: Update dev.sh to be able to just do this without this step
      - name: Prepare quakebuild
        run: |
          docker build --cache-from type=gha --cache-to type=gha,mode=max \
            -f ./dev/Dockerfile.quake -t quakebuild dev

      - name: Refresh Dev
        run: sh dev.sh build_pk3
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pak100.pk3
          path: base/hf/pak100.pk3